#!/usr/bin/env bash

# Carrega função para aplicar o tema e o tema de cores
source ~/.config/suckless/scripts/dwmblocks/sb-carrega-tema-dwmblocks

## Carrega o brilho da tela
valor_brilho=$(brightnessctl | awk '/%/ {print$4}' | cut -c 2-4 | sed 's/%//' | sed 's/)//')
temperatura=$(xrandr --verbose | awk '/Gamma/ {print $2}' | cut -d: -f3 | head -1)

## Variaveis que serão passadas a função
icone="󰃠"
cor_forte=$COLOR_2
cor_fraca=$COLOR_9

## Antigo método antes dda função
# brilhoIcone="$icone_redshift^b$COLOR_1^^c$COLOR_BACKGROUND^ 󰃠 ^d^^c$COLOR_BACKGROUND^^b$COLOR_9^ $brilho ^d^"

# Monta o retorno do dwmblocks pela função aplicar_tema
brilhoIcone=$(aplicar_tema "$icone" "$valor_brilho" "$cor_forte" "$cor_fraca")

# Apresentacao condicionada
case "$OPERATION_MODE" in
    "MINIMO")
        echo ""
    ;;
    "MEDIO")
        echo ""
    ;;
    *)
        echo "$brilhoIcone"
    ;;
esac

# funcoes cliclaveis
case $BUTTON in
    4) bash ~/.config/suckless/scripts/dwm/dwm-brilho-tela-aumenta ;;
    5) bash ~/.config/suckless/scripts/dwm/dwm-brilho-tela-diminui ;;
    6) setsid -f st -e emacs -nw "$0" ;;
#    9) bash ~/.config/suckless/scripts/dwm/dwm-redshift-aumenta ;;
#    10) bash ~/.config/suckless/scripts/dwm/dwm-redshift-diminui ;;
    9)
        case "$temperatura" in
            1.0)
                redshift -P -O 6000
                notify-send -t 3000 "Alterado a temperatura para 6000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.1)
                redshift -P -O 5500
                notify-send -t 3000 "Alterado a temperatura para 5500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.2)
                redshift -P -O 5000
                notify-send -t 3000  "Alterado a temperatura para 5000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.3)
                redshift -P -O 4500
                notify-send -t 3000  "Alterado a temperatura para 4500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.4)
                redshift -P -O 4200
                notify-send -t 3000  "Alterado a temperatura para 4200K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.5)
                redshift -P -O 4000
                notify-send -t 3000  "Alterado a temperatura para 4000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.6)
                redshift -P -O 3850
                notify-send -t 3000  "Alterado a temperatura para 3850K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.7)
                redshift -P -O 3700
                notify-send -t 3000  "Alterado a temperatura para 3700K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
        esac

    ;;
    10)
        case "$temperatura" in
            1.1)
                redshift -P -O 6500
                notify-send -t 3000 "Alterado a temperatura para 6500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.2)
                redshift -P -O 6000
                notify-send -t 3000 "Alterado a temperatura para 6000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.3)
                redshift -P -O 5500
                notify-send -t 3000 "Alterado a temperatura para 5500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.4)
                redshift -P -O 5000
                notify-send -t 3000  "Alterado a temperatura para 5000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.5)
                redshift -P -O 4500
                notify-send -t 3000  "Alterado a temperatura para 4500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.6)
                redshift -P -O 4200
                notify-send -t 3000  "Alterado a temperatura para 4200K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.7)
                redshift -P -O 4000
                notify-send -t 3000  "Alterado a temperatura para 4000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.8)
                redshift -P -O 3850
                notify-send -t 3000  "Alterado a temperatura para 3850K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
        esac

    ;;
esac

exit 0
