#!/usr/bin/env bash

# Carrega função para aplicar o tema e o tema de cores
source ~/.config/suckless/scripts/dwmblocks/sb-carrega-tema-dwmblocks

clock=$(date '+%I')

case "$clock" in
	"00") icon="󱑊" ;;
	"01") icon="󱐿" ;;
	"02") icon="󱑀" ;;
	"03") icon="󱑁" ;;
	"04") icon="󱑂" ;;
	"05") icon="󱑃" ;;
	"06") icon="󱑄" ;;
	"07") icon="󱑅" ;;
	"08") icon="󱑆" ;;
	"09") icon="󱑇" ;;
	"10") icon="󱑈" ;;
	"11") icon="󱑉" ;;
	"12") icon="󱑊" ;;
esac

relogio=$(aplicar_tema $icon $(date '+%H:%M') $COLOR_1 $COLOR_9)
relogio_modificado="${relogio::-1}"
echo "$relogio_modificado"

day=$(date "+%d")
image="/usr/share/icons/Numix/64/places/calendar-$day.svg"

case $BUTTON in
    1) dunstify "📅 Compromissos de Hoje $(date +'%d/%m')" "$(calcurse -a | tail -n +2 | sed 's/^[[:space:]]*- /  • /')" -t 10000 ;;
    3) dunstify "$(cal -3 | head -n1)" "$(cal -3 | tail -n+2 | sed "/^[[:space:]]*$/d;s/$(date '+%e')\b/<span background='#282828' foreground='#ebdbb2'>$(date '+%e')<\/span>/g;s/  /<span>  <\/span>/g")" ;;
    6) setsid -f st -e emacs -nw "$0" ;;
esac

exit 0
