#!/usr/bin/env bash

# Carrega o tema
source $HOME/.theme_selected


# Carrega função para aplicar o tema e o tema de cores
source ~/.config/suckless/scripts/dwmblocks/sb-carrega-tema-dwmblocks

# funcoes cliclaveis
case $BUTTON in
    1) potctl -t ;;
    3) $HOME/.config/suckless/scripts/dmenu/dmenu-pomodoro ;;
    4) potctl -i ;;
    5) potctl -d ;;
	6) setsid -f st -e emacs -nw "$0" ;;
    8) potctl -s ;;
    9) potctl -I ;;
    10) potctl -D ;;
esac

# Verifica se tem algum pomodoro rodando
PID_pomodoro=$(potctl | awk '{print$2}' | tail -1)
if [[ -z "$PID_pomodoro" ]]; then
    echo ""
else
    # Coleta informacoes nesse segundo
    pomodoro_minutos=$(potctl -1 | awk '{print$2}')
    pomodoro_modo=$(potctl -1 | awk '{print$1}')
    pomodoro_cont=$(potctl -1 | awk '{print$4}')
    pomodoro_pause=$(potctl | awk '{print$4}' | tail -1)

    # Verifica o modo em que o pomodoro esta, e classifica o icone e a cor com base nisso
    case $pomodoro_modo in
        "PM")
            icone="󱎫"
            color="$COLOR_3"
            color2="$COLOR_11"
        ;;
        "SB")
            icone=""
            color="$COLOR_5"
            color2="$COLOR_13"
        ;;
        "LB")
            icone=""
            color="$COLOR_6"
            color2="$COLOR_14"
        ;;
    esac

    # Altera o icone quando o pomodoro esta pausado
    if [ "$pomodoro_pause" = "Yes" ]; then
        icone="󱫞"
        color="$COLOR_1"
        color2="$COLOR_9"
    fi

    # Gera notificacao quando muda de modo
    if [ "24:59" = "$pomodoro_minutos" ] && [ "PM" = "$pomodoro_modo" ]; then
        notify-send -t 3000 "Pomodoro Inicio" "Iniciado Pomodoro 25min" --icon="$THEME_ICON_DUNST/24x24/panel/pomodoro-start-light.svg"
    fi

    if [ "04:59" = "$pomodoro_minutos" ] && [ "SB" = "$pomodoro_modo" ]; then
        notify-send -t 3000 "Pomodoro Pausa Curta" "Iniciado Pausa curta 5m" --icon="$THEME_ICON_DUNST/24x24/panel/pomodoro-start-light.svg"
    fi

    if [ "14:59" = "$pomodoro_minutos" ] && [ "LB" = "$pomodoro_modo" ]; then
        notify-send -t 3000 "Pomodoro Pausa Longa" "Iniciado Pausa longa 15min" --icon="$THEME_ICON_DUNST/24x24/panel/pomodoro-start-light.svg"
    fi

    # Gera som quando finaliza o modo
    if [ "00:01" = "$pomodoro_minutos" ]; then
        # ffplay -nodisp -autoexit -t 3 /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga &
        # $HOME/.config/suckless/scripts/others/som
        diretorio="$HOME/.config/suckless/assets/audio"
        
        # Encontra todos os arquivos MP3 no diretório
        arquivos_mp3=("$diretorio"/*.mp3)

        # Seleciona um arquivo aleatório
        arquivo_aleatorio="${arquivos_mp3[RANDOM % ${#arquivos_mp3[@]}]}"

        # Toca o arquivo MP3
        echo "Tocando: $(basename "$arquivo_aleatorio")"
        ffplay -nodisp -autoexit -t 5 "$arquivo_aleatorio" &

    fi

    # retorno no dwmblocks
    output=$(aplicar_tema "$icone" "$pomodoro_minutos  $pomodoro_cont" "$color" "$color2")
    echo "$output"
    #echo "^b$color^^c$COLOR_BACKGROUND ^ $icone ^d^^c$COLOR_BACKGROUND^^b$color2^ $pomodoro_minutos  $pomodoro_cont ^d^ "
fi

exit 0
