animations = (
{
  triggers = ["size"]
  scale-x = {
      curve = "cubic-bezier(0.175, 0.885, 0.32, 1.275)";
      start = "window-width-before / window-width";
      end = 1;
      duration = 0.2
  };
  scale-y = {
      curve = "cubic-bezier(0.175, 0.885, 0.32, 1.275)";
      start = "window-height-before / window-height";
      end = 1;
      duration = 0.2
  };
  offset-x = {
      curve = "cubic-bezier(0.175, 0.885, 0.32, 1.275)";
      start = "window-x-before - window-x";
      duration = 0.2
      end = 0;
  };
  offset-y = {
      curve = "cubic-bezier(0.175, 0.885, 0.32, 1.2)";
      start = "window-y-before - window-y";
      duration = 0.2
      end = 0;
  };

  shadow-scale-y = "scale-y";
  shadow-scale-x = "scale-x";
},
)
