# Aqui estão as rádios que encontrei na internet

[Animu]
stream = https://stream.animu.moe/320?0.36743537670543347=
site = https://www.animu.moe/
data = 2026-04-21
tags = Anime, Músicas Moe, Rádio
local = "São Paulo"

[89FM Radio Rock]
stream = https://27353.live.streamtheworld.com/RADIO_89FM_ADP.aac?dist=site-89fm&_t=1776772986447
site = https://www.radiorock.com.br/
data = 2026-04-21
tags = Rock
local = "São Paulo"

[Kiss FM]
stream = https://23043.live.streamtheworld.com/RADIO_KISSFM_ADP.aac?dist=RadiosNet&1776775157658
site = http://www.kissfm.com.br
data = 2026-04-21
tags = Pop-Rock, Classic Rock
local = "São Paulo"

[LISTEN.moe]
stream = https://listen.moe/fallback
site = https://listen.moe
data = 2026-04-21
tags = Anime, Rock
local = "US"
