#!/usr/bin/env bash

# Obtém a temperatura atual do monitor
temperatura=$(xrandr --verbose | awk '/Gamma/ {print $2}' | cut -d: -f3 | head -1)

aumentar="Aumentar"
diminuir="Diminuir"
toggle="Toggle"

# Variable passed to dmenu
options="$toggle\n$aumentar\n$diminuir"

chosen="$(echo -e "$options" | dmenu -p "Menu RedShift - Temperatura atual é: $temperatura" )"
case $chosen in
    "$aumentar")
        case "$temperatura" in
            1.0)
                redshift -P -O 6000
                notify-send -t 3000 "Alterado a temperatura para 6000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.1)
                redshift -P -O 5500
                notify-send -t 3000 "Alterado a temperatura para 5500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.2)
                redshift -P -O 5000
                notify-send -t 3000  "Alterado a temperatura para 5000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.3)
                redshift -P -O 4500
                notify-send -t 3000  "Alterado a temperatura para 4500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.4)
                redshift -P -O 4200
                notify-send -t 3000  "Alterado a temperatura para 4200K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.5)
                redshift -P -O 4000
                notify-send -t 3000  "Alterado a temperatura para 4000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.6)
                redshift -P -O 3850
                notify-send -t 3000  "Alterado a temperatura para 3850K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.7)
                redshift -P -O 3700
                notify-send -t 3000  "Alterado a temperatura para 3700K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
        esac

    ;;
    "$diminuir")
        case "$temperatura" in
            1.1)
                redshift -P -O 6500
                notify-send -t 3000 "Alterado a temperatura para 6500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.2)
                redshift -P -O 6000
                notify-send -t 3000 "Alterado a temperatura para 6000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.3)
                redshift -P -O 5500
                notify-send -t 3000 "Alterado a temperatura para 5500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.4)
                redshift -P -O 5000
                notify-send -t 3000  "Alterado a temperatura para 5000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.5)
                redshift -P -O 4500
                notify-send -t 3000  "Alterado a temperatura para 4500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.6)
                redshift -P -O 4200
                notify-send -t 3000  "Alterado a temperatura para 4200K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.7)
                redshift -P -O 4000
                notify-send -t 3000  "Alterado a temperatura para 4000K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
            1.8)
                redshift -P -O 3850
                notify-send -t 3000  "Alterado a temperatura para 3850K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
                ;;
        esac

    ;;
    "$toggle")
        if (( $(echo "$temperatura >= 1.3" | bc -l) )); then
            redshift -P -O 6500
            notify-send -t 3000 "󰛨 Modo Diurno" "Alterado a temperatura para 6500K" --icon="/usr/share/icons/ePapirus/16x16/actions/colors-chromablue.svg"
        else
            redshift -P -O 4500
            notify-send -t 3000 "󱩍 Modo Noturno" "Alterado a temperatura para 4500K" --icon="/usr/share/icons/ePapirus/16x16/actions/redeyes.svg"
        fi

    ;;
esac
