#!/usr/bin/env bash

# Carrega o tema
source $HOME/.theme_selected

pactl set-source-volume @DEFAULT_SOURCE@ -5%
volume=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep "Volume" | awk '{print$5}' | sed 's/%//')

# Atualiza dwmblocks
kill -10 $(pidof dwmblocks)

notify-send -t 3000 "Volume microfone $volume" "Diminuído 5% do volume do microfone" --icon="$THEME_ICON_DUNST/16x16/devices/audio-input-microphone.svg"
