#!/usr/bin/env bash

# Carrega o tema
source $HOME/.theme_selected

# Toca som de switch
ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga

# Atualiza dwmblocks
kill -46 $(pidof dwmblocks)

sleep .1

# Verificar o estado atual do Num Lock
NUMLOCK_STATE=$(xset q | grep "Num Lock:" | awk '{print $8}')

if [ "$NUMLOCK_STATE" == "on" ]; then
    num="󰎠"
    texto_notify="Numlock ON"
    icon="num-lock-on.svg"
else
    num=""
    texto_notify="Numlock OFF"
    icon="num-lock-off.svg"
fi

# mostra notificacao de uso do capslock
notify-send -t 3000 "$texto_notify" "" --icon="$THEME_ICON_DUNST/24x24/panel/$icon"
