#!/usr/bin/env bash

# Carrega o player atual
source ~/.cache/playerctl_selecionado

# Roda o comando
playerctl --player=$PLAYER_SELECIONADO next

# Envia notificacao
~/.local/bin/playerctl_songinfo

# Atualiza dwmblocks   tem atualizao no playerctl_songinfo
kill -10 $(pidof dwmblocks)
