#!/usr/bin/env bash

# Carrega o tema
source $HOME/.theme_selected


brightnessctl -q set 5%-
brilho=$(brightnessctl | awk '/%/ {print$4}' | cut -c 2-4 | sed 's/%//' | sed 's/)//')

# Atualiza dwmblocks
kill -10 $(pidof dwmblocks)


notify-send -t 3000 "Brilho diminuído em 5%" "Brilho total $brilho%" --icon="$THEME_ICON_DUNST/16x16/actions/brightnesssettings.svg"
