static void cleanup_config(void);
static void load_config(void);
static void load_command_settings(const config_t *cfg);
static void load_image_settings(const config_t *cfg);
static void load_functionality_settings(const config_t *cfg);
static void load_button_bindings_settings(const config_t *cfg);
static void load_button_settings_for(const config_setting_t *bindings_t, button_t **buttons, int *num_button_bindings);
static void load_keybindings_settings(const config_t *cfg);
static void load_options_settings(const config_t *cfg);
static void load_thumbnail_settings(const config_t *cfg);
static void load_window_settings(const config_t *cfg);
static void load_main_settings(const config_t *cfg);
static void load_zoom_levels(const config_setting_t *zoom_levels_t);
static void load_fallback_config(void);
static void add_key_binding(unsigned int mask, KeySym keysym, cmd_f function, appmode_t mode, int argument);
static void add_button_binding(button_t **buttons, int *num_button_bindings, unsigned int mask, KeySym keysym, cmd_f function, appmode_t mode, int argument);
static unsigned int parse_modifier(const char *string);
static KeySym parse_keysym(const char *string);
static cmd_f parse_function(const char *string, appmode_t *mode);
static int parse_function_int_constant(const char *string);
