[urgency_low]
    frame_color = "#BD93F9"
	background = "#414559"
	foreground = "#cad3f5"

[urgency_normal]
    frame_color = "#BD93F9"
	background = "#1e2030"
	foreground = "#b8c0e0"

[urgency_critical]
    frame_color = "#BD93F9"
    background = "#ed8796"
	foreground = "#f4dbd6"
