[urgency_low]
    frame_color = "#002b36"
    background = "#eff1f5"
	foreground = "#4c4f69"

[urgency_normal]
    frame_color = "#002b36"
    background = "#dce0e8"
	foreground = "#4c4f69"

[urgency_critical]
    frame_color = "#002b36"
    background = "#f4b8e4"
	foreground = "#4c4f69"
