[urgency_low]
    frame_color = "#f8f8f2"
    background = "#ffffff"
	foreground = "#44475a"

[urgency_normal]
    frame_color = "#f8f8f2"
    background = "#f0f0f0"
	foreground = "#44475a"

[urgency_critical]
    frame_color = "#f8f8f2"
    background = "#ffb86c"
	foreground = "#44475a"
