[urgency_low]
    background = "#fbf1c7"
    foreground = "#3c3836"
    frame_color = "#ebdbb2"

[urgency_normal]
    background = "#fbf1c7"
    foreground = "#3c3836"
    frame_color = "#ebdbb2"

[urgency_critical]
    background = "#fbf1c7"
    foreground = "#cc241d"
    frame_color = "#9d0006"
