
[urgency_low]
    background = "#2E3440"
    foreground = "#D8DEE9"
    timeout = 3
    frame_color = "#4C566A"

[urgency_normal]
    background = "#3B4252"
    foreground = "#E5E9F0"
    timeout = 6
    frame_color = "#5E81AC"

[urgency_critical]
    background = "#BF616A"
    foreground = "#ECEFF4"
    timeout = 0
    frame_color = "#BF616A"
