[urgency_low]
	background = "#fdf6e3"
	foreground = "#657b83"
    frame_color =  "#fdf6e3"

[urgency_normal]
	background = "#eee8d5"
	foreground = "#586e75"
    frame_color =  "#fdf6e3"

[urgency_critical]
	background = "#dc322f"
	foreground = "#fdf6e3"
    frame_color =  "#fdf6e3"
