[urgency_low]
    frame_color = "#1a1a2e"
	background = "#2d2d44"
	foreground = "#00ffff"

[urgency_normal]
    frame_color = "#1a1a2e"
	background = "#2d2d44"
	foreground = "#ff66cc"

[urgency_critical]
    frame_color = "#1a1a2e"
	background = "#ff0066"
	foreground = "#e0e0e0"
