[urgency_low]
    frame_color = "#f2f2f2"
	background = "#dcdce7"
	foreground = "#00cccc"

[urgency_normal]
    frame_color = "#f2f2f2"
	background = "#dcdce7"
	foreground = "#ff66cc"

[urgency_critical]
    frame_color = "#f2f2f2"
	background = "#ff3399"
	foreground = "#4a4a6a"
