# Theme: xresources
# Updated from .Xresources on qua 22 jul 2026 15:08:09 -03

[urgency_low]
    background = "#2E3440"
    foreground = "#bf616a"
    frame_color = "#2E3440"

[urgency_normal]
    background = "#2E3440"
    foreground = "#ECEFF4"
    frame_color = "#2E3440"

[urgency_critical]
    background = "#2E3440"
    foreground = "#81a1c1"
    frame_color = "#2E3440"
