# Theme: xresources
# Updated from .Xresources on seg 20 jul 2026 09:53:41 -03

[urgency_low]
    background = "#002b36"
    foreground = "#dc322f"
    frame_color = "#002b36"

[urgency_normal]
    background = "#002b36"
    foreground = "#839496"
    frame_color = "#002b36"

[urgency_critical]
    background = "#002b36"
    foreground = "#6c71c4"
    frame_color = "#002b36"
