#!/usr/bin/env bash
###############################################################################
##
## Usage
##
##     ./$(basename "$0")     # Update xresources theme and restart dunst
##     ./$(basename "$0") -h  # Show help
##
## Description
##
##     This script updates the dunst 'xresources' theme with colors from
##     .Xresources and restarts dunst to apply changes.
##
###############################################################################

set -e

# Help
if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    cat << EOF
Usage: ./$(basename "$0")

Description:
    Updates the dunst 'xresources' theme with colors from .Xresources
    and restarts dunst to apply the changes.

Options:
    -h, --help     Show this help message

Example:
    ./$(basename "$0")     # Update theme and restart dunst
EOF
    exit 0
fi

# Check if xrdb is installed
if ! command -v xrdb &> /dev/null; then
    printf 'Error: xrdb not found.\nInstall xorg-xrdb (Arch) or x11-xserver-utils (Debian/Ubuntu).\n'
    exit 1
fi

# Directories
readonly CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dunst"
readonly THEME_FILE="$CONFIG_DIR/themes/xresources.conf"
readonly BASE_CONF="$CONFIG_DIR/dunst-base.conf"
readonly DUNSTRC="$CONFIG_DIR/dunstrc"

# Check if theme exists
if [[ ! -f "$THEME_FILE" ]]; then
    echo "Error: Theme file not found: $THEME_FILE"
    echo "Create it first with:"
    echo "  mkdir -p $CONFIG_DIR/themes"
    echo "  cp /path/to/template.conf $THEME_FILE"
    exit 1
fi

# Check if base config exists
if [[ ! -f "$BASE_CONF" ]]; then
    echo "Error: Base config not found: $BASE_CONF"
    echo "Please ensure dunst-base.conf exists in $CONFIG_DIR"
    exit 1
fi

# Function to get color from X resources directly from xrdb
get_color() {
    local value
    # Query xrdb directly (works for *color1, *background, etc.)
    value="$(xrdb -query 2>/dev/null | grep "^\\*$1:" | head -n1 | cut -d: -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

    # If not found with *, try without
    if [[ -z "$value" ]]; then
        value="$(xrdb -query 2>/dev/null | grep "^$1:" | head -n1 | cut -d: -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    fi

    # Return value or default
    printf '%s' "${value:-$2}"
}

echo "=== Updating xresources theme ==="
echo ""

# Get colors from .Xresources directly from xrdb
BG="$(get_color 'dwm.titlenormbgcolor' '#1a1a2e')"
FG="$(get_color 'dwm.titlenormfgcolor' '#d8d8d8')"

# Use colorX for different urgencies
COLOR1="$(get_color 'dwm.tag5' '#ff77ff')"  # Pink - Critical
COLOR2="$(get_color 'dwm.tag2' '#9c64e8')"  # Purple - Normal
COLOR4="$(get_color 'dwm.tag3' '#ff5a8f')"  # Pink/Red - Low

# Also try to get dwm colors as fallback
DWM_SEL="$(get_color 'dwm.selfgcolor' '')"
DWM_URG="$(get_color 'dwm.urgbordercolor' '')"
DWM_TAG1="$(get_color 'dwm.tag1' '')"

# If color1 is not found, try dwm colors
if [[ "$COLOR1" == "#1a1a2e" ]] || [[ -z "$COLOR1" ]]; then
    COLOR1="${DWM_URG:-#ff0066}"
fi

if [[ "$COLOR2" == "#1a1a2e" ]] || [[ -z "$COLOR2" ]]; then
    COLOR2="${DWM_TAG2:-#9c64e8}"
fi

if [[ "$COLOR4" == "#1a1a2e" ]] || [[ -z "$COLOR4" ]]; then
    COLOR4="${DWM_TAG1:-#ff77ff}"
fi

echo "Colors from .Xresources:"
echo "  Background: $BG"
echo "  Foreground: $FG"
echo "  Color1 (critical): $COLOR1"
echo "  Color2 (normal): $COLOR2"
echo "  Color4 (low): $COLOR4"
echo ""

# Update the theme file
cat > "$THEME_FILE" << EOF
# Theme: xresources
# Updated from .Xresources on $(date)

[urgency_low]
    background = "$BG"
    foreground = "$COLOR4"
    frame_color = "$BG"

[urgency_normal]
    background = "$BG"
    foreground = "$FG"
    frame_color = "$BG"

[urgency_critical]
    background = "$BG"
    foreground = "$COLOR1"
    frame_color = "$BG"
EOF

echo "✓ Theme file updated: $THEME_FILE"
echo ""

# Generate complete dunstrc
echo "Generating dunstrc..."
{
    echo "# Dunst configuration file"
    echo "# Generated by $(basename "$0") on $(date)"
    echo "# Theme: xresources"
    echo ""
    cat "$BASE_CONF"
    echo ""
    echo "# Theme: xresources (colors from .Xresources)"
    echo ""
    cat "$THEME_FILE"
} > "$DUNSTRC"

echo "✓ Configuration saved to: $DUNSTRC"
echo ""

# Restart dunst
echo "Restarting Dunst..."
if systemctl --user is-active --quiet dunst.service 2>/dev/null; then
    systemctl --user restart dunst.service
else
    killall dunst 2>/dev/null || true
    sleep 0.5
    dunst 2>/dev/null &
fi

# Verify restart
sleep 1
if pgrep -x "dunst" > /dev/null; then
    echo "✓ Dunst restarted successfully!"
    echo ""
    echo "Test with: notify-send 'Test' 'Hello from dunst!'"
else
    echo "⚠ Dunst may not have started. Check:"
    echo "  journalctl --user -u dunst.service -n 20"
    echo "  dunst -conf $DUNSTRC -test"
fi
